export const pricingData = [
  {
    name: "Launch",
    subtitle: "A site you can edit yourself",
    price: "$450",
    priceUnit: "starting",
    timeline: "Delivered in 1–2 weeks",
    features: [
      "Drag-and-drop or hand-coded site",
      "Up to 6 pages",
      "Mobile-responsive layout",
      "Editable without a developer",
    ],
    buttonText: "Start with Launch",
    buttonLink: "#contact",
    isPopular: false,
  },
  {
    name: "Build",
    subtitle: "A full-stack web application",
    price: "$1,800",
    priceUnit: "starting",
    timeline: "Delivered in 3–6 weeks",
    features: [
      "Custom frontend and backend",
      "Database, auth, and APIs",
      "Deployed to your own AWS account",
      "CI/CD so updates ship themselves",
    ],
    buttonText: "Start with Build",
    buttonLink: "#contact",
    isPopular: true,
  },
  {
    name: "Scale",
    subtitle: "Web, app, and infrastructure",
    price: "Custom",
    priceUnit: "quote",
    timeline: "Scoped after a short call",
    features: [
      "Everything in Build",
      "iOS / Android app on the same backend",
      "Production infra: EC2, Docker, Nginx",
      "Ongoing support window included",
    ],
    buttonText: "Talk it through",
    buttonLink: "#contact",
    isPopular: false,
  },
];
